config/routes.rb
Rails.application.routes.draw do
  resources :todotasks
  #get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todotask.rb
class Todotask < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/todotasks_controller.rb
class TodotasksController < ApplicationController
  before_action :set_todotask, only: %i[ show edit update destroy ]

  # GET /todotasks or /todotasks.json
  def index
    @todotasks = Todotask.all
  end

  # GET /todotasks/1 or /todotasks/1.json
  def show
  end

  # GET /todotasks/new
  def new
    @todotask = Todotask.new
  end

  # GET /todotasks/1/edit
  def edit
  end

  # POST /todotasks or /todotasks.json
  def create
    @todotask = Todotask.new(todotask_params)

    respond_to do |format|
      if @todotask.save
        format.html { redirect_to @todotask, notice: "Todotask was successfully created." }
        format.json { render :show, status: :created, location: @todotask }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todotask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todotasks/1 or /todotasks/1.json
  def update
    respond_to do |format|
      if @todotask.update(todotask_params)
        format.html { redirect_to @todotask, notice: "Todotask was successfully updated." }
        format.json { render :show, status: :ok, location: @todotask }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todotask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todotasks/1 or /todotasks/1.json
  def destroy
    @todotask.destroy
    respond_to do |format|
      format.html { redirect_to todotasks_url, notice: "Todotask was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todotask
      @todotask = Todotask.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todotask_params
      params.require(:todotask).permit(:task_name, :duedate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todotasks_helper.rb
module TodotasksHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Списък със задачи', todotasks_path, class:"navbar-brand" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Нова задача', new_todotask_path, class:"navbar-brand" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is my first Rails Webpage

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>To Do List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
    <h1><%= yield %></h1>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/todotasks/_form.html.erb
<%= form_with(model: todotask) do |form| %>
  <% if todotask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todotask.errors.count, "error") %> prohibited this todotask from being saved:</h2>

      <ul>
        <% todotask.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :task_name %>
    <%= form.text_field :task_name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :duedate %>
    <%= form.date_select :duedate, class:"form-select" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/todotasks/edit.html.erb
<h1>Editing Todotask</h1>

<%= render 'form', todotask: @todotask %>

<%= link_to 'Show', @todotask %> |
<%= link_to 'Back', todotasks_path %>

app/views/todotasks/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped table-bordered table-hover" >
  <thead class="table-dark">
    <tr>
      <th>Задача</th>
      <th>Крайна дата</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todotasks.each do |todotask| %>
      <tr>
        <td><%= todotask.task_name %></td>
        <td><%= todotask.duedate %></td>
        <td><%= link_to 'Show', todotask %></td>
        <td><%= link_to 'Edit', edit_todotask_path(todotask) %></td>
        <td><%= link_to 'Destroy', todotask, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todotask', new_todotask_path, class:"btn btn-secondary" %>

app/views/todotasks/new.html.erb
<h1>Добавяне на задача!</h1>

<%= render 'form', todotask: @todotask %>

<%= link_to 'Back', todotasks_path %>

app/views/todotasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Задача:</strong>
  <%= @todotask.task_name %>
</p>

<p>
  <strong>Крайна дата:</strong>
  <%= @todotask.duedate %>
</p>

<%= link_to 'Edit', edit_todotask_path(@todotask), class:"btn btn-secondary" %>
<%= link_to 'Back', todotasks_path, class:"btn btn-secondary" %>